#! /bin/sh

# Test manconv's handling of incomplete characters at end of file.

: ${srcdir=.}
. "$srcdir/testlib.sh"

: ${MANCONV=manconv}

init

printf '\314' >"$tmpdir/1.inp"  # 0xCC
expect_pass 'incomplete character at EOF' '! run $MANCONV -f EUC-JP -t UTF-8//IGNORE <"$tmpdir/1.inp" >/dev/null'

finish
