#! /bin/sh

# Basic mandb tests.

: ${srcdir=.}
. "$srcdir/testlib.sh"

: ${MANDB=mandb}
: ${ACCESSDB=accessdb}

init
fake_config /usr/share/man
MANPATH="$tmpdir/usr/share/man"
export MANPATH
db_ext="$(db_ext)"

write_page test 1 "$tmpdir/usr/share/man/man1/test.1.gz" UTF-8 gz t \
	'test \- simple mandb test'
run $MANDB -C "$tmpdir/manpath.config" -u -q "$tmpdir/usr/share/man"
echo 'test -> "- 1 1 MTIME A - - gz simple mandb test"' >"$tmpdir/1.exp"
accessdb_filter "$tmpdir/usr/share/man/index$db_ext" >"$tmpdir/1.out"
expect_pass 'simple mandb test' 'diff -u "$tmpdir/1.exp" "$tmpdir/1.out"'

finish
